project:
  type: website
  render:
    - "*.qmd"
    - "*.markdown"
  post-render: 
    - R/copy_images_html_data.R
    - R/fixup_citations.R

website:
  title: "Mountain Doodles"
  site-url: https://doodles.mountainmath.ca
  repo-url: https://github.com/mountainMath/mountain_doodles
  description: "Thoughts on housing, demographics and random things"
  reader-mode: true
  open-graph: true
  favicon: images/favicon.ico
  twitter-card: 
    creator: "@vb_jens"
  navbar:
    logo: images/mm_stamp_small.png
    right:
      - about.qmd
      - text: Archive
        href: archive.qmd
      - icon: github
        href: https://github.com/mountainMath/mountain_doodles
        aria-label: GitHub
      # - text: "{{< fa brands bluesky >}}"
      #   href: https://bsky.app/profile/jensvb.bsky.social
      #   aria-label: Bluesky
      - icon: twitter
        href: https://twitter.com/vb_jens
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/vb-jens/
        aria-label: LinkedIn
      - icon: envelope-at-fill
        href: mailto:jens@mountainmath.ca
        aria-label: Email
      - icon: rss
        href: index.xml
        aria-label: RSS
  sidebar:
    - id: sidebar-main
      style: "docked"
      search: false
      tools:
      - icon: github
        href: https://github.com/mountainMath
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/vb_jens
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/vb-jens/
        aria-label: LinkedIn
      - icon: envelope-at-fill
        href: mailto:jens@mountainmath.ca
        aria-label: Email
      # title: "Mountain Doodles"
      logo: images/profile.jpg
      header: "**Too much data, too little time**"
      footer: Mountain Doodles is an insomnia driven side project, born out of random questions, trying to give partial answers through data. During daytime at [MountainMath](https://mountainmath.ca).
      contents:
        - section: "**CensusMapper**"
          contents:
            - text: "View and create maps based on Canadian census data"
              href: "https://censusmapper.ca"
        - section: "**Book project**"
          contents:
            - text: "Analyzing Canadian Demographic and Housing Data"
              href: "https://mountainmath.github.io/canadian_data/"
        - section: "**R packages (CRAN)**"
          contents:
            - text: "**cancensus**: Access Canadian census data"
              href: "https://mountainmath.github.io/cancensus/"
            - text: "**cansim**: Access StatCan data tables"
              href: "https://mountainmath.github.io/cansim/"
            - text: "**tongfen**: Making fine-geography census data comparable across time"
              href: "https://mountainmath.github.io/tongfen/"
            - text: "**cmhc**: Accessing CMHC data"
              href: "https://mountainmath.github.io/cmhc/"
            - text: "**VancouvR**: Accessing City of Vancouver Open Data"
              href: "https://mountainmath.github.io/VancouvR/"
        - section: "**R packages (GitHub)**"
          contents:
            - text: "**canbank**: Accessing Bank of Canda data"
              href: "https://mountainmath.github.io/canbank/"
            - text: "**canpumf**: Accessing and working with StatCan PUMF data"
              href: "https://mountainmath.github.io/canpumf/"
        - section: "**Archives**"
          contents:
            - text: "Previous version of Mountain Doodles"
              href: "mountaindoodles-archived.netlify.app"
        - section: "Other Canadian data focused blogs:"
          contents:
            - text: "HomeFreeSociology"
              href: "https://homefreesociology.com"
            - text: "Dmitry Shkolnik's blog"
              href: "https://www.dshkol.com"
            - text: "Simon Coulombe's blog"
              href: "https://www.simoncoulombe.com"
            - text: "Finances of the Nation"
              href: "https://financesofthenation.ca/category/commentary/"
            - text: "Deny’s Substack"
              href: "https://deny.substack.com"
            - text: "Alex Usher's blog"
              href: "https://higheredstrategy.com/author/alex/"
    - id: sidebar-posts
      style: "docked"
      search: false
      tools:
      - icon: github
        href: https://github.com/mountainMath
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/vb_jens
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/vb-jens/
        aria-label: LinkedIn
      - icon: envelope-at-fill
        href: mailto:jens@mountainmath.ca
        aria-label: Email
      # title: "Mountain Doodles"
      logo: images/profile.jpg
      header: "**Too much data, too little time**"
      footer: Mountain Doodles is an insomnia driven side project, born out of random questions, trying to give partial answers through data. During daytime at [MountainMath](https://mountainmath.ca).

  google-analytics: 
    tracking-id: "UA-54516567-1"
    anonymize-ip: true
    #storage: "none" # need this to be set to "cookies" in order to show up in google analytics
  cookie-consent: false
  comments:
    giscus:
      theme:
        light: "light"
        dark: "dark_dimmed"
      repo: mountainmath/mountain_doodles
      repo-id: R_kgDOLuoDtA
      category: "Blog posts"
      category-id: "DIC_kwDOLuoDtM4Cetfc"
      loading: "lazy"
      language: "en"
      input-position: "bottom"
      reactions-enabled: true
#      strict: "0"
      mapping: "pathname"
# filters:
#   - code-filename

format:
  html:
    theme: 
      light: css/mountainmath_light.scss
      dark: css/mountainmath_dark.scss
    css: css/styles.css
    page-layout: full
    #toc-location: 'left'
    mainfont: "Roboto"
    code-overflow: wrap
    code-fold: true
    code-folding: hide
    code-summary: "\\<code\\>"
    code-copy: hover
    grid:
      sidebar-width: 400px
#      margin-width:	250px
editor: source

